### ISSUE TITLE
[Feature]: Save each gif after gen during batch

### ISSUE THREAD

**Issue by GuruVirus** [continue-revolution/sd-webui-animatediff#108] opened 2023-09-20 18:49 UTC
### Expected behavior

With t2i, each image gets saved after being gen'd so I can see the final outcome while the rest of the batch is going.
With this extension, I have to wait until the entire batch is done before being able to review the individual gifs.
I would like it to save after each one is finished.

**Comment by continue-revolution** [comment] 2023-09-20 18:55
duplicate of #97

**Closed by continue-revolution** 2023-09-20 18:55 UTC
