### ISSUE TITLE
[Bug]: Attribute error

### ISSUE THREAD

**Issue by advo-kat** [continue-revolution/sd-webui-animatediff#5] opened 2023-07-18 09:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

An AttributeError is thrown.

### Steps to reproduce the problem

Press generate while extension is enabled

### What should have happened?

It should not throw the error

### Commit where the problem happens

webui: v1.4.1
extension: [e8c88a4](https://github.com/continue-revolution/sd-webui-animatediff/commit/e8c88a40cf1f5ddb3c3a60cb325d09fa81102081)

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--listen --api --enable-insecure-extension-access
```

### Console logs

```Shell
2023-07-18 19:38:03,650 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet input blocks.
Error running postprocess: C:\Users\TooDee\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
Traceback (most recent call last):
  File "C:\Users\TooDee\stable-diffusion-webui\modules\scripts.py", line 404, in postprocess
    script.postprocess(p, processed, *script_args)
  File "C:\Users\TooDee\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 142, in postprocess
    self.remove_motion_modules(p)
  File "C:\Users\TooDee\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 122, in remove_motion_modules
    unet.input_blocks[unet_idx].pop(-1)
  File "C:\Users\TooDee\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'TimestepEmbedSequential' object has no attribute 'pop'
```
```


### Additional information

_No response_

**Comment by mbazaczek** [comment] 2023-07-18 10:03
I am experiencing the same error, seems like there is an issue when unloading the motion module. Restarting the whole webui.bat allows for one successful generation, afterwards I'm getting weird noise unless I restart the webui.bat.

**Comment by IntellectzProductions** [comment] 2023-07-18 11:15
> I am experiencing the same error, seems like there is an issue when unloading the motion module. Restarting the whole webui.bat allows for one successful generation, afterwards I'm getting weird noise unless I restart the webui.bat.

yes. this is annoying. For me my generation doesn't even make a gif.

**Comment by continue-revolution** [comment] 2023-07-20 04:46
Please give me a screenshot of your webui, otherwise I cannot reproduce your error on my side.

**Comment by AkosseDeVamp** [comment] 2023-07-21 10:20
> Please give me a screenshot of your webui, otherwise I cannot reproduce your error on my side.

Hello, I'm not the OP but I have the same error. The Webui is up-to-date and I installed this addon about 30 minutes ago so I assume this is as well. I have included a screenshot, hope it helps.

![msedge_IidFxkI2G3](https://github.com/continue-revolution/sd-webui-animatediff/assets/140162395/51a083ca-35cf-4e20-bc02-f9758d102a96)

**Comment by antispamtutoruser123** [comment] 2023-07-23 04:12
Yep same error and same symptoms with all images going to garbage after first run.

**Comment by antispamtutoruser123** [comment] 2023-07-23 04:26
I fixed it by reinstalling torch.  Check for error messages on the window where you launched webui

**Comment by remixer-dec** [comment] 2023-09-06 22:30
For old pytorch there is a solution:

```python
def _pop(self, key):
    v = self[key]
    del self[key]
    return v

def _insert(self, index, module):
        n = len(self._modules)
        if not (-n <= index <= n):
            raise IndexError(
                f'Index out of range: {index}')
        if index < 0:
            index += n
        for i in range(n, index, -1):
            self._modules[str(i)] = self._modules[str(i - 1)]
        self._modules[str(index)] = module
        return self

TimestepEmbedSequential.pop = _pop
TimestepEmbedSequential.insert = _insert
```
in scripts/animatediff.py somewhere after imports

**Comment by continue-revolution** [comment] 2023-09-14 01:16
I will close this issue for now. If you meet this problem again, please update your pytorch by running webui with --reinstall-torch (if I remember correctly)

**Closed by continue-revolution** 2023-09-14 01:16 UTC
