### ISSUE TITLE
[Bug]: The first 8 frames and the last 8 frames of the generated 16 frames are very different.

### ISSUE THREAD

**Issue by sciart17** [continue-revolution/sd-webui-animatediff#16] opened 2023-07-20 03:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

The first 8 frames and the last 8 frames of the generated 16 frames are very different. 

![00020-3187489593](https://github.com/continue-revolution/sd-webui-animatediff/assets/33056525/1b70a400-3134-49f6-bd7f-01c1011d05e2)

### Steps to reproduce the problem

![Snipaste_2023-07-20_11-35-22](https://github.com/continue-revolution/sd-webui-animatediff/assets/33056525/9cb67150-0a49-4b9a-a249-e49d76e64680)

### What should have happened?

-

### Commit where the problem happens

webui: v1.4.1-2-g7390dd0
extension:  b574ca0

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
N/A
```

**Comment by continue-revolution** [comment] 2023-07-20 04:29
Duplicate of #4

**Closed by continue-revolution** 2023-07-20 04:29 UTC
