### ISSUE TITLE
[Bug]: prompt character limit issue

### ISSUE THREAD

**Issue by antispamtutoruser123** [continue-revolution/sd-webui-animatediff#33] opened 2023-07-25 00:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Long prompts cause the image to change after 8 frames

The original repo can handle longer prompts before this happens.  Using the same prompt on this plugin version doesn't work.

### Steps to reproduce the problem

A photo of a female with a voluminous afro hairstyle, dyed in vibrant shades of
    teal and purple. She wears a stylish streetwear ensemble, consisting of a graphic
    t-shirt, oversized denim jacket, and high-waisted jogger pants. A backdrop of
    colorful street art and neon signs reflects the vibrant energy of the urban environment
    she inhabits. Epic character composition, sharp focus and natural lighting. The
    subsurface scattering effect adds a touch of ethereal glow, while the f2 aperture
    and 35mm lens create a perfect balance of depth and detail

### What should have happened?

It should generate a single stable animation that doesn't toggle midway through.

### Commit where the problem happens

webui: 1.4.1
extension: [287b30af] Mon Jul 24 16:07:19 2023

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
No error message
```

**Comment by continue-revolution** [comment] 2023-07-26 23:01
Indeed. Duplicate of #4. Refer to https://github.com/continue-revolution/sd-webui-animatediff/issues/36#issuecomment-1652652211 for my response.

**Closed by continue-revolution** 2023-07-26 23:01 UTC
